//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G2PO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("G2PO.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string AddTextToUpper {
            get {
                return ResourceManager.GetString("AddTextToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        public static string AddToFavoritesText {
            get {
                return ResourceManager.GetString("AddToFavoritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string AppBarButtonNextText {
            get {
                return ResourceManager.GetString("AppBarButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser.
        /// </summary>
        public static string AppBarButtonOpenInBrowserText {
            get {
                return ResourceManager.GetString("AppBarButtonOpenInBrowserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string AppBarButtonPreviousText {
            get {
                return ResourceManager.GetString("AppBarButtonPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a feed.
        /// </summary>
        public static string AppBarMenuItemAddText {
            get {
                return ResourceManager.GetString("AppBarMenuItemAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedcast.
        /// </summary>
        public static string ApplicationTitleToLower {
            get {
                return ResourceManager.GetString("ApplicationTitleToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDCAST.
        /// </summary>
        public static string ApplicationTitleToUpper {
            get {
                return ResourceManager.GetString("ApplicationTitleToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string BusinessCategoryTitleText {
            get {
                return ResourceManager.GetString("BusinessCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string CategoryPageAppBarPreviousText {
            get {
                return ResourceManager.GetString("CategoryPageAppBarPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string ContextMenuPinToStartText {
            get {
                return ResourceManager.GetString("ContextMenuPinToStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ContextMenuRemoveText {
            get {
                return ResourceManager.GetString("ContextMenuRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string EntertainmentCategoryTitleText {
            get {
                return ResourceManager.GetString("EntertainmentCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fashion.
        /// </summary>
        public static string FashionCategoryTitleText {
            get {
                return ResourceManager.GetString("FashionCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesCategoryTitleText {
            get {
                return ResourceManager.GetString("FavoritesCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthCategoryTitleText {
            get {
                return ResourceManager.GetString("HealthCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select categories to initially populate your reader. You can add or remove categories later..
        /// </summary>
        public static string InitialDescriptionText {
            get {
                return ResourceManager.GetString("InitialDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string InitialFinishedButtonText {
            get {
                return ResourceManager.GetString("InitialFinishedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error downloading new articles, please check your connection..
        /// </summary>
        public static string InitialLoadingFailedText {
            get {
                return ResourceManager.GetString("InitialLoadingFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up your reader, please wait.
        /// </summary>
        public static string InitialLoadingText {
            get {
                return ResourceManager.GetString("InitialLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated 1 minute ago.
        /// </summary>
        public static string LastUpdatedText {
            get {
                return ResourceManager.GetString("LastUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string MainPageAllText {
            get {
                return ResourceManager.GetString("MainPageAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string MainPageAppBarAddText {
            get {
                return ResourceManager.GetString("MainPageAppBarAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string MainPageAppBarRefreshText {
            get {
                return ResourceManager.GetString("MainPageAppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featured.
        /// </summary>
        public static string MainPageFeaturedText {
            get {
                return ResourceManager.GetString("MainPageFeaturedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPageSettingsTitleText {
            get {
                return ResourceManager.GetString("MainPageSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi downloads only.
        /// </summary>
        public static string MainPageSettingsWifiText {
            get {
                return ResourceManager.GetString("MainPageSettingsWifiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new.
        /// </summary>
        public static string MainPageWhatsNewText {
            get {
                return ResourceManager.GetString("MainPageWhatsNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string MusicCategoryTitleText {
            get {
                return ResourceManager.GetString("MusicCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string NewCategoryAppBarSaveText {
            get {
                return ResourceManager.GetString("NewCategoryAppBarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a category name and select existing feeds you would like to add to such category..
        /// </summary>
        public static string NewCategoryDescriptionText {
            get {
                return ResourceManager.GetString("NewCategoryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new category.
        /// </summary>
        public static string NewCategoryTextToLower {
            get {
                return ResourceManager.GetString("NewCategoryTextToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW CATEGORY.
        /// </summary>
        public static string NewCategoryTitleText {
            get {
                return ResourceManager.GetString("NewCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string NewFeedAppBarSaveText {
            get {
                return ResourceManager.GetString("NewFeedAppBarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string NewFeedAppBarSearchText {
            get {
                return ResourceManager.GetString("NewFeedAppBarSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category to add this feed to..
        /// </summary>
        public static string NewFeedCategoryDescriptionText {
            get {
                return ResourceManager.GetString("NewFeedCategoryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results to display..
        /// </summary>
        public static string NewFeedNoResultsText {
            get {
                return ResourceManager.GetString("NewFeedNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a feed name or URL to search for..
        /// </summary>
        public static string NewFeedSearchDescriptionText {
            get {
                return ResourceManager.GetString("NewFeedSearchDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new feed.
        /// </summary>
        public static string NewFeedTextToLower {
            get {
                return ResourceManager.GetString("NewFeedTextToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW FEED.
        /// </summary>
        public static string NewFeedTitleText {
            get {
                return ResourceManager.GetString("NewFeedTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsCategoryTitleText {
            get {
                return ResourceManager.GetString("NewsCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics.
        /// </summary>
        public static string PoliticsCategoryTitleText {
            get {
                return ResourceManager.GetString("PoliticsCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string SportsCategoryTitleText {
            get {
                return ResourceManager.GetString("SportsCategoryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string TechnologyCategoryTitleText {
            get {
                return ResourceManager.GetString("TechnologyCategoryTitleText", resourceCulture);
            }
        }
    }
}
